# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Build

on:
  push:
    branches:
      -Development
      -master

  schedule:
    - cron: '00 08 * * *'

jobs:
  Angular_Build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max-old-space-size=8192
    if: github.ref == 'refs/heads/Development' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: |
          npm ci
          node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng build
